# Generated by Django 5.0 on 2023-12-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Post',
        ),
    ]
